name: Upload Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: devops-aws-cicd
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: 4haIzkxPIYxNYftiDXm3HrKWPuw5aNp4nnrZa0cs
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'website'  # Change if your files are in a different directory

      
